version: '3.1'

services:
  mongo:
    image: mongo
    ports: 
    - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    networks:
    - freecrvs

  web:
    image: docker.pkg.github.com/afoone/freecrvs/freecrvs
    ports: 
      - 3000:3000
    environment: 
      - MONGODB_URI=mongodb://mongo:27017/gambia?retryWrites=true&w=majority
      - MONGODB_DB=gambia
      - JWT_KEY=KDJSALIOOOOOKDJ092348KDSJFJ023
      - NEXTAUTH_URL=/
      - NEXT_PUBLIC_BASE_URL=http://draman.iprocuratio.com:3000/
    networks:
    - freecrvs

networks: 
  freecrvs:
    external: true
