version: '3.1'

services:
  web:
    image: docker.pkg.github.com/afoone/freecrvs/freecrvs
    ports: 
      - 3000:3000
    environment: 
      - MONGODB_URI=mongodb://mongo:27017/gambia?retryWrites=true&w=majority
      - MONGODB_DB=gambia
      - JWT_KEY=KDJSALIOOOOOKDJ092348KDSJFJ023
      - NEXTAUTH_URL=http://draman.iprocuratio.com/
      - NEXT_PUBLIC_BASE_URL=http://draman.iprocuratio.com/
    networks:
    - freecrvs
    - traefik
    deploy:
      replicas: 2
      labels:
        - 'traefik.enable=true'
        - 'traefik.frontend.rule=Host: draman.iprocuratio.com'
        - 'traefik.port=3000'
        - 'traefik.docker.network=traefik'


networks: 
  freecrvs:
    external: true
  traefik:
    external: true
