version: "3.3"

services:
  traefik:
    image: traefik:1.7.16
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik/acme.json:/acme.json
    configs:
      - source: traefik
        target: /etc/traefik/traefik.toml
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - opencrvs


networks:
  opencrvs:
    external: true

configs:
  traefik:
    external: true
